Repository shift-happens-benchmark/icml-2022, pull requests merged in 2022-07, with the labels that each got.

#71 add logo file
  docs/source/_static/logos/ShiftHappens_Logo.png
Labels: documentation

#78 Add contributor statement
  CONTRIBUTING.rst
Labels: enhancement

#73 Update LICENSE file
  LICENSE
Labels: documentation

#74 Remove python version in black
  .pre-commit-config.yaml
Labels: enhancement

#88 Update schedule.csv
  docs/source/schedule.csv
Labels: website

#75 Add global configuration options
  docs/source/api.rst
  shifthappens/config.py
  shifthappens/data/imagenet.py
  tests/test_config.py
Labels: enhancement
